---

package: plato.utilities.parser.parse_dstc2
class: Parser
arguments:
  data_path: data/dstc2_traindev/data
  ontology: example/domains/CamRestaurants-rules.json
  database: example/domains/CamRestaurants-dbase.db
